package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        adicionarListeners();
    }

    private void adicionarListeners() {
        itmDiscentes.addActionListener(e -> {
            DiscenteTela discenteTela = new DiscenteTela(this, true);
            discenteTela.setVisible(true);
        });

        itmProfessores.addActionListener(e -> {
            ProfessorTela professorTela = new ProfessorTela(this, true);
            professorTela.setVisible(true);
        });

        itmDisciplinas.addActionListener(e -> {
            DisciplinaTela disciplinaTela = new DisciplinaTela(this, true);
            disciplinaTela.setVisible(true);
        });

        itmMatriculas.addActionListener(e -> {
            MatriculaTela matriculaTela = new MatriculaTela(this, true);
            matriculaTela.setVisible(true);
        });

        itmTurmas.addActionListener(e -> {
            TurmaTela turmaTela = new TurmaTela(this, true);
            turmaTela.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        itmDiscentes = new javax.swing.JMenuItem();
        itmProfessores = new javax.swing.JMenuItem();
        itmDisciplinas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmMatriculas = new javax.swing.JMenuItem();
        itmTurmas = new javax.swing.JMenuItem();
        mnuSistema = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle Acadêmico");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Controle Acadêmico");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Selecione uma opção no menu \"Cadastros\" para começar.");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                                        .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(274, 274, 274))
        );
        pnlPrincipalLayout.setVerticalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubtitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
        );

        mnuCadastros.setText("Cadastros");

        itmDiscentes.setText("Discentes (Alunos)");
        mnuCadastros.add(itmDiscentes);

        itmProfessores.setText("Professores");
        mnuCadastros.add(itmProfessores);

        itmDisciplinas.setText("Disciplinas");
        mnuCadastros.add(itmDisciplinas);
        mnuCadastros.add(jSeparator1);

        itmMatriculas.setText("Matrículas");
        mnuCadastros.add(itmMatriculas);

        itmTurmas.setText("Turmas");
        mnuCadastros.add(itmTurmas);

        jMenuBar1.add(mnuCadastros);

        mnuSistema.setText("Sistema");

        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        mnuSistema.add(itmSair);

        jMenuBar1.add(mnuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmSairActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem itmDiscentes;
    private javax.swing.JMenuItem itmDisciplinas;
    private javax.swing.JMenuItem itmMatriculas;
    private javax.swing.JMenuItem itmProfessores;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmTurmas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}